### ISSUE TITLE
[BUG] Trails iterator error

### ISSUE THREAD

**Issue by OmarRinaz** [Unnamed-Company/LittleOrionEngine#255] opened 2020-08-11 15:30 UTC
**Describe the bug**
when i use a trail component the engine crashes

**To Reproduce**
1. go to my computer, 
2. execute the a clean scene 
3. put a new game object
4. put a trail component on the game object
5. move the object 
6. crash

**Expected behavior**
i expect the trail to work and not crash the application

**Screenshots**
![image](https://user-images.githubusercontent.com/11278484/89916767-4e48fd00-dbf8-11ea-889a-cea7f80b919b.png)

**Additional context**
I may have also memory problems but couldnt replicate them

**Comment by yalania** [comment] 2020-08-12 08:26
here try https://github.com/OnionGalaxy/LittleOrionEngine/blob/develop/Engine/Component/ComponentTrail.cpp#L100 add it = test_points.erase(it);

**Comment by Misarte** [comment] 2020-08-14 16:06
Try pulling the latest commit, then delete Library and any logs or build options, then Rebuild the Engine and Build in Release. Let me know if the issue persists, because for me this error doesn't occur and I can not reproduce. In my latest code Line 103 is:  it = test_points.erase(it);

**Comment by mariofv** [comment] 2020-09-22 19:18
Fixed in #269

**Closed as completed by mariofv** 2020-09-22 19:18 UTC
Labels: bug
