### ISSUE TITLE
[BUG] 2 states playing at the same time

### ISSUE THREAD

**Issue by JoanStinson** [Unnamed-Company/LittleOrionEngine#84] opened 2020-04-22 17:48 UTC
**Describe the bug**
If you have 3 states. State 1 goes out to state 2 with priority 0 and goes out to state 3 with priority 1 if you select activate in Animation component without any trigger (leaving it empty), it plays both states at the same time when playing.

**To Reproduce**
1. Create a state machine with 3 states
2. Add out from default state to the other two with exit time and different priority values
3. Go to animation component and place animation state
4. Leave trigger input field empty and select Activate button (notice another animation box appears)
5. Play the state machine and notice how two animations play at the same time

**Expected behavior**
Only the state animation with highest priority should play.

**Comment by JordiRomagosa** [comment] 2020-05-02 11:50
I can't reproduce this bug. Might be because the triggers are not currently working.
Currently, after the state 1 ends, it continues with the state with higher priority and ignores the other. And Activate button does nothing.

**Comment by yalania** [comment] 2020-05-09 17:29
I coudn't reproduce this either, so I will close it.

**Closed as completed by yalania** 2020-05-09 17:29 UTC
Labels: bug
