### ISSUE TITLE
[BUG] Looped second state animation in state machine

### ISSUE THREAD

**Issue by JoanStinson** [Unnamed-Company/LittleOrionEngine#82] opened 2020-04-22 17:28 UTC
**Describe the bug**
After creating a second state in a state machine, the second animation gets looped and can't get out of it, even if you put an out condition or the condition is not set to loop, so it should play once.

**To Reproduce**
1. Create a new state machine
2. Add 3 states
3. Attach state 1 to state 2 with exit time and state 2 to state 3 with exit time
4. Play state machine and notice in inspector second animation gets looped and doesn't access 3rd state

**Expected behavior**
If the second animation state is not set as "Loop" the animation should play once, if its set with exit time and attached to another state it should play once and then play the animation on the next state.

**Comment by JordiRomagosa** [comment] 2020-05-02 11:40
With this state machine:
![imagen](https://user-images.githubusercontent.com/9912719/80863015-8b0c6c00-8c79-11ea-8d07-4b064488b1df.png)
![imagen](https://user-images.githubusercontent.com/9912719/80863023-952e6a80-8c79-11ea-8456-8b08ce758ec2.png)

I got this result. As you can see, it does not get stuck on the second state (in a loop) and continues to play the third state:
![Zombunny](https://user-images.githubusercontent.com/9912719/80863133-5b119880-8c7a-11ea-87fb-2d1713f75438.gif)

**Comment by yalania** [comment] 2020-05-09 17:25
![giphy](https://user-images.githubusercontent.com/48101863/81480559-c9ca9500-922a-11ea-89ae-bd37e30c96b8.gif)

I was unable to reproduce this one either, so I will close it

**Closed as completed by yalania** 2020-05-09 17:25 UTC
Labels: bug
