### ISSUE TITLE
[BUG] After using the Remove Texture Button new textures doesn't load

### ISSUE THREAD

**Issue by JorxSS** [Unnamed-Company/LittleOrionEngine#115] opened 2020-05-13 01:02 UTC
**Describe the bug**
If you remove all the textures from a material and then try to add a new one, that texture does not load.

**To Reproduce**
1. Select a Game Object with a Material component
2. Remove all the textures added with the button "Remove Texture"
3. Drag n drop a new texture.

**Expected behavior**
The possibility to load and remove all the textures I want.

**Screenshots**
![30fbd7598d8490cceab1194056b19842](https://user-images.githubusercontent.com/49075678/81759848-1b428080-94c6-11ea-8b5e-f42a1e9faaca.gif)

**Comment by mariofv** [comment] 2020-05-18 13:49
Because we cannot reproduce this, I close this atm. Please reopen this.

**Closed as completed by mariofv** 2020-05-18 13:49 UTC
Labels: bug
